### ISSUE TITLE
ł char

### ISSUE THREAD

**Issue by texrg** [atlas-engineer/next#121]
Sorry but i cant use ł and other polish (AltGr (right) + letter) chars.
change it!

**Comment by jmercouris** [comment]
I would like to, but, you'll have to provide me with a little bit more information to debug with :D

On my machine, Greek, and other foreign characters work just fine 

![screen shot 2018-09-27 at 16 26 26](https://user-images.githubusercontent.com/1691662/46152836-1d64b680-c272-11e8-97f5-483f04e7cf74.png)


please list:
1. OS
2. Version of Software

what happens when you try to enter the characters?
what if you copy and paste the characters, does it allow you to copy them anywhere?
