### ISSUE TITLE
[Debian/GTK] Next wont open

### ISSUE THREAD

**Issue by j3kyl** [atlas-engineer/next#154]
Hi, As instructed I have installed all dependencies, **make all** and run it with ./next-gtk-webkit.

Still, it just hangs and not run next at all. 

**GDB** indicates that I don't have a glibc poll.c installed. But I have all glibc packages installed even libc6. Maybe its a debian issue

Any help?

Thanks! 

-----------------------------

Debian SID
Lenovo T430
make all output: https://pastebin.com/frBLBACk
GDB output: https://pastebin.com/sYm36Ssp
Debian dependencies:
```
~ λ sudo apt install sbcl libwebkit2gtk-4.0-dev sqlite glib-networking-services gsettings-desktop-schemas
[sudo] password for j3kyl: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
glib-networking-services is already the newest version (2.58.0-1).
gsettings-desktop-schemas is already the newest version (3.28.1-1).
sbcl is already the newest version (2:1.4.14-1).
sqlite is already the newest version (2.8.17-15).
libwebkit2gtk-4.0-dev is already the newest version (2.22.4-1).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
```

**Comment by Ambrevar** [comment]
What do you mean with

> run ti with ./next-gtk-webkit

?  `./next-gtk-webkit` is not the full program, it's a platform port expecting instruction from the Lisp core, otherwise it won't do anything.

You need to start `./next` instead.  If `next-gtk-webkit` is found in the path, or fully specified by the `*gtk-webkit-command*` variable, then it will automatically launch the platform port.

See the developer readme for the full details: 
https://github.com/atlas-engineer/next/blob/master/documents/README.org

**Comment by j3kyl** [comment]
LMAO... that is why! Sorry! hehehe

**Comment by j3kyl** [comment]
r
