### ISSUE TITLE
BUG: incorret results using search via search-engines ("s term")

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#210]
Hi, 

Next User Manual(outdated) state that searching with search-engines,  users must use  **c-l "s search-term"**

But, instead of returning a duckduckgo.com page it uses the current visited website search engine.

Eg: If user is visiting github.com, Next **"s cnn"** uses github internal search engine, returning a "cnn" from its repositories. 

screenshot01: https://i.ibb.co/z6J0Dz1/2019-05-13-204418-1366x768-scrot.png

Same goes for most sites as reddit, stackoverflow.

Using **m-l,** Next returns a blank page.
screenshot02: https://i.ibb.co/YD6tbr1/2019-05-13-204408-1366x768-scrot.png

I noticed that with the recent release,  its not required anymore to use **"s"**, as **c-l "cnn"** return ddg pages. thats even better.

I reckon that is a great feature.  Though,  a simetric key letter as **"c cnn"** requiring current visited site search engine would be interesting.

And **"s cnn"** for duckduckgo.

-------------------------------------
Next: Guix sbcl-next
OS: Debian SID 11

**Comment by Ambrevar** [comment]
That's a lot of title changes ;)

Thanks for reporting this.  There were two issues indeed:

- First the documentation was out of date, the `s` search prefix does not exist anymore.  To use the default search engine (DuckDuckGo) you need no prefix anymore.

- Second there was an issue with invalid URLs that didn't start with a search prefix.  This should now be fixed with ff18601baede6aae088786b19c5c7f46b71edb78.

Thanks for reporting and feel free to re-open if there is an issue.

**Comment by alexanderbarbosa** [comment]
@Ambrevar lol
