### ISSUE TITLE
Reopen closed tab

### ISSUE THREAD

**Issue by lxbarbosa** [atlas-engineer/next#253]
Hi,

Yet another feature would that of reopening just recently closed tab.

Thanks!

**Comment by Ambrevar** [comment]
I think this would amount to keeping the history of a buffer in memory.
Should we keep just one history?  All of them?  A configurable amount?  I'd vote for the latter ;)

**Comment by jmercouris** [comment]
It is not about keeping the history of a buffer in memory, it is about keeping a history of buffers that have existed in memory. I think this is part of a more generalized solution/problem. Perhaps events should never be destructive, and all actions should be on a stack of limited height (so that we can eventually garbage collect things).

So every action has a converse action, kill buffer, make buffer etc. So when you "undo", you perform the reverse action to reverse the side effects. Or maybe we can somehow restore back to previous state somehow. I don't know exactly, this would need some more thinking.

**Comment by Ambrevar** [comment]
> It is not about keeping the history of a buffer in memory, it is about
> keeping a history of buffers that have existed in memory.

I don't understand the difference (beside the plural).

Regarding the more general problem, I believe you are true, but this
seems rather hard.
The most obvious use case is restoring tabs, and I believe we can
implement that quite easily.  As you said, let's think a little more
about it and see what comes up.

**Comment by Ambrevar** [comment]
The specific problem of reopening buffers could be implemented another way: By re-using the code for session persistence.

**Comment by jmercouris** [comment]
Very true, but that makes it a much larger problem for a new contributor to approach.

**Comment by 4t0m** [comment]
I just started working on this feature, and I'm noticing that the killed-buffer-history has a lot in common with the recently added clipboard ring (#349).

Being new to lisp, I'm wondering if the ring management in that file is the most efficient way to handle things.  I had initially just been thinking I'd create a list, push and pop from it, and enforce the size-limit manually, but it looks like arrays are the tool for the job.

Almost all of the code in [ring.lisp](https://github.com/atlas-engineer/next/blob/3257f79316437c71926876bf2bc13ccb308007ff/source/ring.lisp) would apply to the buffer-history-ring as well, but it would have to be possible to set the array size separately for the clipboard-ring and the buffer-history-ring.  So, I'm also wondering if we could/should separate the clipboard-specific stuff from that file and then elsewhere define these two rings?

Otherwise I can just write up the ring management separately for this feature, but it seems wasteful. 

Thanks!  And sorry for taking so long to get started on this!

**Comment by Ambrevar** [comment]
@4t0m Great news, glad you are picking this one up!

Indeed, storing the buffer history in a ring makes a lot of sense, considering that "ring" is just a fancy name for "history structure" :)

You can already instantiate a buffer-history-ring of a custom length this way:

``` lisp
(make-instance 'ring :items (make-array 123 :initial-element nil))
```
This is not very pretty though, so a `make-ring` constructor would be very welcome. @noogie13 ?

**Comment by 4t0m** [comment]
Thanks @Ambrevar!  

There's one other thing I'm wondering about (so far!).  I'm still thinking about it, but I'd appreciate any guidance.

1. I'm not sure where to run the code for "store the buffer-url in history".  It seems like the place where the buffer is actually deleted is `rpc-buffer-delete`, so I'm thinking it makes sense to put it there because then it only needs to be added in one place.  Does that seem right?  And would I define the method in buffer.lisp or somewhere else?

Sorry for all of the questions.  (Especially with how trivial it's looking like this will be!)

**Comment by Ambrevar** [comment]
Yes, this seems right indeed! :)

The buffer history should probably be stored in the remote-interface
class, so I think the method can go there as well.

No worries about the questions, keep asking! :p

**Comment by 4t0m** [comment]
Okay, I think I put it where you're saying.  We'll see when I submit the code...

My next question is how to deal with removing items from the ring when tabs are re-opened.

I think I can do this by adding a `tail-index`* to [ring.lisp](https://github.com/noogie13/next/blob/4eae7dd7e25503169f0d7ba51411ba4518cbf351/source/ring.lisp), so, when I remove an item from the front of the ring I would increment `tail-index`.  I would have to change the rest of the file to start counting at `tail-index` instead of 0.

Is there some better solution?  Is it okay to change `ring.lisp` like that?  Maybe I should make some class that extends `ring`?  Let me know!

* `head-index` makes more sense to me, but that's being used for the index of the oldest item.

**Comment by Ambrevar** [comment]
- Previously you mentioned that ring.lisp had some clipboard-specific code.  Indeed, it has the `ring-insert-clipboard' method.  I wonder if this method should be put elsewhere, e.g. in `minibuffer.lisp`.  @noogie13?

- Ring deletion is not implemented yet, and it's obvious that we need it now :)  Feel free to propose a patch for `ring.lisp`.  You don't need `tail-index` as the index of the last element is `(mod (+ (head-index ring) (item-count ring)) (ring-size ring))` if I'm not mistaken.  You could add `tail-index` method that does just this, if this comes up multiple times.

- Naming question: "buffer history" is confusing because it's unclear whether it's the history of a specific buffer of the list of closed buffers.  So maybe name it `recent-buffers`?

**Comment by Ambrevar** [comment]
Something else to consider: Now we have a `open-external-link-in-new-window-p` slot for `remote-interface` (which we should rename by the way), so depending on its value, the undo function should make use the current window or make a new one, as appropriate.

So I think the right function to call here is `make-buffers`.  I'd like to factor this function with `make-buffer`.  @vindarel, thoughts?

**Comment by noogie13** [comment]
> * Previously you mentioned that ring.lisp had some clipboard-specific code.  Indeed, it has the `ring-insert-clipboard' method.  I wonder if this method should be put elsewhere, e.g. in `minibuffer.lisp`.  @noogie13?

That would be fine, sure. Just make the change with the PR adding the buffer-history, right?

**Comment by 4t0m** [comment]
Should this be closed?

**Comment by jmercouris** [comment]
You are correct, this should be closed :)
