### ISSUE TITLE
Right-Click Floating Menu

### ISSUE THREAD

**Issue by nolanwrightdev** [atlas-engineer/next#278]
You know when you right-click on a link and a little floating menu appears to the side, displaying quite a few different options? It says _Open Link_, _Open Link in New Window_, etc. Yeah, so that menu works pretty wonky on Next. Most of the time when I right click, the menu appears for a split second and then immediately disappears. If I keep the right button pressed down, the menu stays put until I mouse-up. Okay, and then the _Open Link_ option works fine, but the _Open Link in New Window_ is a no-op, doesn't do anything. All this happens pretty consistently for me.

Is this stuff supposed to work as of now?

**Comment by jmercouris** [comment]
This is a known issue, we are working on improving support :)

**Comment by Ambrevar** [comment]
Indeed, the behaviour you are describing is exactly the state of things
for now: this is because the is no specific implementation of the
context menu in Next for now, we fallback on the default which is not
appropriate.

And yes, you need to keep the button pressed for now, this is also a
known issue.  Will work on it after the 1.3 release.

**Comment by Ambrevar** [comment]
The disappearing menu is fixed on master.  For the content of the menu itself, see #688.
