### ISSUE TITLE
Unacceptable TLS certificate

### ISSUE THREAD

**Issue by arkhan** [atlas-engineer/next#296]
Regards, I am trying to enter a site with a self-generated certificate with openssl, but next it only shows me the message: Unacceptable TLS certificate and does not allow me to accept the same

Thanks

**Comment by Ambrevar** [comment]
How did you install Next?

Which website is it?
If you don't want to share a specific website URL, can you reproduce
with another one?

**Comment by arkhan** [comment]
install next on archlinux from AUR, the specific site is https://intra.ec.krugercorp.com

**Comment by Ambrevar** [comment]
Can reproduce on a local build too, this is not AUR-specific.
Strange...  There is something wrong on the WebKitGTK side.  I'll investigate.

**Comment by Ambrevar** [comment]
I've looked into this.

Firefox does not report an invalid certificate, but it seems that all
other webkit-based browsers do (at least on Guix).  Epiphany has the
same issue.  Not sure why there is a difference.

Anyways, bad certificates must be handled, otherwise it makes it
impossible to browse pages that force to HTTPS with a wrong certificate.
We need two things:

- Support a whitelist in `init.lisp` of websites for which to ignore bad
  certificates.

- Support live, temporary by-passing of bad URL.

The WebKitGTK API has
`webkit_web_context_allow_tls_certificate_for_host` which does the job,
but it seems that this function can only be called after the
`load-failed-with-tls-errors` has been emitted, that is to say, after
the loading has failed.  So for both cases above, it means that the user
_has_ to reload the page in order for WebKit to bypass the certificate
check.

Unless I'm misunderstanding the API, this is very inconvenient.
Anyone?

Otherwise we need to ask upstream.

**Comment by crocodile2u** [comment]
Affects me as well. Ubuntu 19.04, self-signed certificate on a dev website. Renders NEXT unusable ((

**Comment by Ambrevar** [comment]
Yes, hopefully the next architectural change with regard to the platform
port will make it easier to  fix this issue.  Stay tuned! :)

**Comment by Ambrevar** [comment]
certificate-whitelist-mode restored!
