### ISSUE TITLE
(define-key :scheme :vi-normal "H" 'switch-buffer-previous) doesn't work

### ISSUE THREAD

**Issue by glacambre** [atlas-engineer/next#318]
I added the following bindings to my init.lisp:
```lisp
(add-to-default-list 'vi-normal-mode 'buffer 'default-modes)
(define-key :scheme :vi-normal "H" 'switch-buffer-previous)
```
Pressing `H` doesn't switch to the previous buffer. Instead, it seems to reload the page. This is especially weird since running `switch-buffer-previous` directly from the command line works as expected and `switch-buffer-previous` correctly appears as being bound to `H` in the completion buffer.

**Comment by alexanderbarbosa** [comment]
weird, adding those two line do what you want in my config.

**Comment by Ambrevar** [comment]
The problem is with mode order.  The first mode has priority.
By default, the modes for regular buffers are

(get-default 'buffer 'default-modes)

Changes are that `document-mode` comes before `root-mode`.

`history-backwards` belongs to `document-mode`, while
`switch-buffer-previous` belongs to root-mode.
So doing what you did, the "H" binding will be found first in
document-mode, effectively shadowing the one in root-mode.

A few options:

1. You can unset "H" from document mode first, then bind what you want:

```
(define-key :scheme :vi-normal :mode 'document-mode "H" nil)
(define-key :scheme :vi-normal "H" 'switch-buffer-previous)
```

2. You can create a new mode, e.g. `my-mode`, add the binding there, and
add the mode in first position:

```
(add-to-default-list 'my-mode 'buffer 'default-modes)
```


Regarding your question about the minibuffer display the right binding,
this is a bug indeed, see pull request #323.

**Comment by Ambrevar** [comment]
For an example of `my-mode`, see https://github.com/atlas-engineer/next/pull/397.
This could be the "new way" of configuring stuff in the future versions of Next.
