### ISSUE TITLE
[Request]: Easier packaging

### ISSUE THREAD

**Issue by rowhit** [atlas-engineer/next#326]
Thanks for wonderful package like next. However, I am finding it harder to build it using the instructions. Here, I am not requesting to help me debug the build issues but rather an easier packaging for the next browser. Few suggestions are standalone deb, rpm packages along with a docker image for someone to quickly evaluate it.

**Comment by Ambrevar** [comment]
Both a `deb` package and `rpm` packages would be very welcome.  I
personally don't use such systems, so contributions are welcome.

As for Docker, we provide both a Guix package and a Guix pack (on the
download page) which supersedes docker.

We tried hard to make the Makefile as smart as possible, so that a
simple `make next` would do the right thing.  If it's not the case for
you, please report, we will improve it further.

**Comment by rowhit** [comment]
Thanks for the response. The build instruction is fine. I was just requesting a frustration free experience for user who just want to try. When I am busy, its very hard to focus and devote time to debug build issues. Just for ex, I am facing lfp.h missing issue although I have already installed the libfixposix. It was just a suggestion.

**Comment by jmercouris** [comment]
Libfixposix is a dependency I would like to see eliminated myself. That involves some work to the d-bus library. I would prefer a pure Common Lisp solution, we'll see where that goes and how long that may take.

**Comment by vindarel** [comment]
related: #76

**Comment by m4zzz** [comment]
On Linux, you might need to run `sudo ldconfig` after installing, otherwise the *nix linker won't be able to find the library

**Comment by Ambrevar** [comment]
Thanks for the tip, but at first glance something really fishy is going
on :p

On which distribution did you have to do that?
Can you provide a recipe?
How did you install Nyxt?

**Comment by m4zzz** [comment]
> How did you install Nyxt?
Well, I followed this (from [Developer README](https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org#gnulinux-gtk-dependencies)
![Screenshot from 2020-12-04 14-48-30](https://user-images.githubusercontent.com/74712937/101145477-d8055600-363f-11eb-911a-67aa3f8f85ff.png)
> On which distribution did you have to do that?
I'm on Ubuntu
Turns out, as for libfixposix, the package you need to install is `libfixposix-dev`.

**Comment by m4zzz** [comment]
@Ambrevar How did you install?
Although I could manage to install the gtk version, I couldn't do it with qt.
I prefer qt to gtk.
Do you have any tips on how to do that?

**Comment by Ambrevar** [comment]
The Qt version is broken at this point.  We need to revamp it, hopefully
sooner than later!  Help welcome! :)
