### ISSUE TITLE
Moving from SQLite to a persistent object datastore

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/next#344]
We are evaluating to move from SQLite to an OO-datastore. Options are bknr.datastore, ubiquitous, cl-prevalence (https://github.com/CodyReichert/awesome-cl#persistent-object-databases).

Reasons are:

- with SQLite, we must handle sqlite versions carefully (we were hit by this already)
- there is work for migrations
- we want full-text search, the module is not built-in (https://www.sqlite.org/fts5.html), and (not (equal CFFI :fun))
- lisp and sqlite data have to be handled separately, which kind of doubles the work
- persisted data is not human readable nor versionable.

All of these would disappear with an s-exp based storage.

We don't think we'd miss SQL much because

- we have very few tables
- our queries are simple, we don't use much SQL
- we don't have lots of thousands of rows

Of the options:

- cl-prevalence seems for an in-memory DB, not to persist much on disk
- ubiquitous seems the easiest, the most automatic, but it doesn't have an OO layer to automatically persist objects. Not sure wether it is meant at storing a DB or a small application configuration (as it states).
- bknr.datastore seems the best fit. ([two example websites](https://www.reddit.com/r/Common_Lisp/comments/cutt25/two_websites_using_bknrdatastore_and_bknrweb/))

**Comment by Ambrevar** [comment]
What about https://github.com/fisxoj/sanity-clause?  Seems to be doubly useful here: we get class slot typing + we can load classes from persisted data (bookmarks, session, history, etc.).

What it may lack:
- Automatic persistence when modifying the object.
- Streaming.

**Comment by Ambrevar** [comment]
Just tested ubiquitous: It actually does persist object automatically, I tested it with

```lisp
(setf (ubiquitous:value :test) "foo")
```
and `/home/ambrevar/.config/common-lisp/ubiquitous/global.conf\\.lisp` was automatically created.

From the readme:
```
Then, when values are set, it automatically saves the configuration to file.
```

@vindarel: What led you to believe that ubiquitous didn't have automatic persistence?  Or did you mean something else?

For now I suggest we go with Ubiquitous.

**Comment by Ambrevar** [comment]
Also see https://github.com/fisxoj/sanity-clause/issues/12

**Comment by Ambrevar** [comment]
My bad, I just realized that Ubiquitous works over a global "storage", not over objects.
This means that a change to the bookmark object does not automatically reflect on the Ubiquitous storage.  I guess this is what @vindarel meant.

Besides, since Ubiquitous storage is global, if we want to persist bookmarks and history separately, we've got to localize the different storage lcoation with the `ubiquitous:with-local-storage` macro.

The question is: do we need automatic persistence?
For history and bookmarks, there are only a limited number of sites where the databases will be changed, so it's easy to persist the data manually.
For the session, it's much harder.  The user can change any buffer details, the modes, the mode slots, etc. at any time.
As a workaround, we could for instance persist the session every time the URL changes.  Not foolproof, but should work most of the time.

**Comment by Ambrevar** [comment]
Another challenge with Ubiquitous: by default the writer prints everything on one line.
For bookmarks in particular, it's important that the user has full control over the serialization format, e.g. persist 1 bookmark per line.  I believe Ubiquitous allows customizing the writer, I'll experiment and see what I can do.

**Comment by Ambrevar** [comment]
I've read the datastore-manual.pdf from http://bknr.net/html/documentation.html and two things stand out:
- The database is stored in a binary form (see page 42).
- There does not seem automatic persistence.  Page 29:
```
Every kind of operation that needs to be logged is called a “transac-
tion”, and such transactions are made explicit in the program code. This
is different from object-oriented databases, where the fundamental trans-
actions are object creation, object deletion and slot access, which are not
special cases in the prevalence model at all.
```

BKNR does not seem to be the right thing for Next.

I'll focus on Ubiquitous for now.

**Comment by Ambrevar** [comment]
I've had a quick look at cl-prevalence:

- Seems to be similar to BKNR in goals.
- It serializes to XML by default, I'm not sure we can easily change this.
- It has almost no documentation beside 2 demos and some tests.
- The bitbucket home page is dead.

I'd say no to cl-prevalence.

**Comment by Ambrevar** [comment]
https://github.com/conspack/cl-conspack was mentioned on https://old.reddit.com/r/Common_Lisp/comments/cyrgu9/library_to_serialize_persist_classes/.
It seems to be able to automatically (de)serialize classes.

**Comment by vindarel** [comment]
as pointed out in reddit, cl-prevalence has a s-exp serializer: https://github.com/40ants/cl-prevalence/blob/master/src/serialization/sexp.lisp

**Comment by Ambrevar** [comment]
Yes, gotta look into that + cl-conspack which must have something similar.

**Comment by Ambrevar** [comment]
[cl-store](https://github.com/skypher/cl-store) has a binary- and an XML backend, nothing for s-exps.

**Comment by Ambrevar** [comment]
cl-conspack does not have an s-exp backend either, and the (de)serializer seems to be very hard coded.

**Comment by Ambrevar** [comment]
Another point: we need to support cyclic data structures.

**Comment by Ambrevar** [comment]
I've had a look at the s-exp (de)serializer of cl-prevalence: it's pretty good!
After defining a serialization method for functions I was able to get a Next buffer serialized!
Any object can have it's own serializer, which allows us to control the formatting / pretty-printing, e.g. have 1 bookmark per line.

To top it all, it support cycles!

**Comment by Ambrevar** [comment]
Another requirement (pfeeew!): We need to leave the (de)serialization and store/restore features fully customizable to the user.  For instance, when we switch to s-exp based storage, some users might prefer a SQL database nonetheless.  Or if we write a Firefox bookmark importer.  Or support for Org bookmark synchronization.

All functions must be independently customizable on a per-object basis.  For instance a user might care about changing the format of bookmarks but not that of the session.

Is there a need to separate the customization of `serialize` and `store`?  Same question for `restore` and `deserialize`.  I believe this is an s-exp-specific implementation detail.  Some storate methods like SQLite might combine both steps into one.

I think 2 customization entry points per feature is good enough, namely `store-function` and `restore-function`.

**Comment by Ambrevar** [comment]
With #371 it seems that cl-prevalence is a very good options for now:
- sexp serializer,
- automatic serialization of any object,
- customizable pretty printing (to some extent -- the deserializer is not really customizable)
- circular data structure support.

Plus we wrote customizable functions to select the store/restore functions.

What's missing:
- Automatic persistence: I don't think we'll need it much at this point, since the session only stores the buffer histories which can only be changed at specific points.
- Streaming: this might be premature optimization for now.  Let's see how Next deals with huge histories in the future.
- Safer deserialization: I don't know if cl-prevelance is as good as sanity-clause to check for type errors when deserializing.  We should investigate.

**Comment by QiangF** [comment]
For better compatibility with other browser bookmarks, maybe use
https://github.com/jarun/Buku
thought is relies on sqlite.

**Comment by Ambrevar** [comment]
Yes, we could definitely support this.
@QiangF Would you be interesting in working on it?
PR welcome! :)

**Comment by QiangF** [comment]
Unfortunately I don't know common lisp, I am working on making oil work with fzf, https://github.com/AndreiUlmeyda/oil
I think using tools like oil can provide a browser agnostic solution.

**Comment by Ambrevar** [comment]
Closing this.
See #465 for a discussion on generic bookmark importers.
