### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by heywoodlh** [atlas-engineer/next#42]
This project is awesome. Is there any way to contribute to this financially? Not like I can offer much but I would so love to support this and make sure it sticks around.

**Comment by jmercouris** [comment]
Hi, thank you very much for the kind words! I am absolutely floored by this!

In fact, this is something I was thinking about myself as I would actually like to turn development of this Browser into a full-time project. I have a couple of ideas I've been considering (all opt-in of course)

0. Classic open source donate button on GitHub repository
1. Patreon type support
2. Opt-in snippet someone can add to their init file to make them use an amazon affiliates code whenever visiting amazon to support us (in order to support this programmatically, I have to finish some functionality involving hooks)
3. Opt-in cryptocurrency mining (e.g. install this lisp package (all open source of course), and configure it to use 5% of your CPU during idle or however)

What are your thoughts on this? Thanks!

-John

**Comment by heywoodlh** [comment]
I think all the options are great. I’ve used both the traditional open source donate button on a Github repo, and I am a Patreon user. I think all of them would be great though. I know people are up in arms about Patreon’s price change but I still use Patreon. So whatever you do, let me know and I will totally contribute.

**Comment by stellarstriker** [comment]
I'd also like to contribute, especially if I can push for certain features like a plugin system or privacy oriented features.

**Comment by jmercouris** [comment]
@stellarstriker 

thank you for your support :)

I am still trying to figure out a model for how to support this project. I will update this thread when I have come up with a model that I will think for the community.

Right now I am currently thinking of offering:

1. Binaries that are paid
2. Installation via apt-get, macports, brew, etc for free

so basically to get simple support and pre-built binaries will cost money, but to just build it from source  yourself will be free. I'm not fully decided yet, and I'll need to see what everyone else thinks, but just more thoughts about this.

**Comment by stellarstriker** [comment]
I'm also on Patreon. It's nice for users to set and forget, and for creators to see recurring moneys.

**Comment by vindarel** [comment]
> Binaries that are paid

I can tell you I really dislike this :S I would not see positively a project that does this and wouldn't even want to try it. 

Also, what if someone else provides binaries ? It's easy to do.

I'm sure there are other and better ways : )  (if a liberapay (the most libre of all)/patreon/bountysource isn't enough)

**Comment by novoid** [comment]
I'm too late for the indiegogo campaign. 
Do you (by chance) do have an IBAN + BIC where I can simply transfer some money?

**Comment by jmercouris** [comment]
@novoid Thank you so much for asking! We are working on setting up something! We do have an official bank account, but not an easy way to pay as it is an American account so I don't think we have IBAN/BIC, not sure though.

**Comment by novoid** [comment]
I'm not an expert in these things but it might be possible that you open up an account for free at https://n26.com/en-at where you get IBAN/BIC which enables free-of-charge money transfer at least for all European people. You can then transfer money in bulk to the US.

**Comment by Ambrevar** [comment]
(Late) update: We now have a Patreon account:
https://www.patreon.com/next_browser

We are also running a new Indiegogo campaign for 1.4!
https://www.indiegogo.com/projects/next-browser-v1-4-0#/
