### ISSUE TITLE
Styles and dark mode

### ISSUE THREAD

**Issue by The-BigDaddy** [atlas-engineer/next#478]
So I started to test out Next for the hell of it.

I wanted to add some extra functionality out of the box, as well as give Next an overall dark theme.

Nothing really game changing, just pretty basic stuff. [Here's my init.lisp](https://pastebin.com/BDcty2Tw)

However, my styles don't seem to load. The `reload-page` command does, and `blocker-mode` is enabled. Just not the styles. I am starting Next with `firejail --ignore=nodbus next`.

Also, and this just might be a `blocker-mode` thing, going from the frontpage of YouTube to sign-in doesn't seem to work. The page just stays idle.

I regards to development or just advanced customization, in order to load all of the libraries and builtin functions Next has in Slime/Sly in Emacs, what should I quickload? Just `(ql:quickload :next)`? Just wondering.

**Comment by Ambrevar** [comment]
Cool config, looks like you are off a good start ;)

Which style does not work as expected precisely?

You've set the "box-style" which is the CSS for the link hints (the name
could be admittedly better).

Currently there is no easy way to set up a "dark mode", but patches are
welcome!  What we would need to implement is a helper function for
setting the CSS style of a buffer.  Nothing really hard here.

Also note that you don't need to set the reload command since it's
already part of the default commands.

I don't know for Youtube, I don't have an account.  Try disabling
blocker-mode if that helps.

**Comment by The-BigDaddy** [comment]
I was hoping to style whatever page I'm on. Basically a poor mans dark mode. Also the styles for the minibuffer are incorrect on my part. I meant the background of the minibuffer to be a dark color.

About developing, would it just be best when developing with Emacs and Sly to quickload all of the packages Next uses? Or would just `(ql:quickload :next)` work?

**Comment by tviti** [comment]
In case it is at all helpful, I have been using the following for my
*dark-mode*:

https://github.com/tviti/next-cfg/blob/master/user-styles.lisp

This does have problems though, namely that it sometimes breaks (goes back to
default styles) when search-hints are activated. Would be interested in seeing
if you figure out a way that deals with around this.

**Comment by Ambrevar** [comment]
@tviti This is really cool!
Interested in sending a PR? ;)

I think I have an idea about the search-hint issue: since we are
crawling the whole HTML document, if something matches in the style if
might apply a style there.

Our current implementation of search-buffer is very clunky.  An easy fix
would be to skip <style> elements at least.

**Comment by Ambrevar** [comment]
Closing in favour of #362.
