### ISSUE TITLE
Remove cl-annot dependency

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#609]
The @export annotation breaks *-edit-definition with SLIME / SLY and it's really annoying.

We can easily replace it with serapeum-style EXPORT* macros.

**Comment by jmercouris** [comment]
Agreed!

**Comment by Ambrevar** [comment]
Fixed in 6f6f2e47d84d3d86d5f9cd6371b0523cc9869ac1.

**Comment by jmercouris** [comment]
While the Serapeum library provides a much nicer macro, I wish it was not named something like `defclass` which shadows the normal defclass in its package, it also makes the signature unwieldy. How do you feel about the idea of making a local name or something of `defexportedclass`?

**Comment by Ambrevar** [comment]
Why is it a problem if it's called `defclass'?  It does not shadow
anything for us since we don't use the package.

Regarding the call, I agree it's too long, so I suggest we use

(trivial-package-local-nicknames:add-package-local-nickname :serax :serapeum.exporting :next)

Then we can simply call

(serax:defclass ...)

Thoughts?

**Comment by jmercouris** [comment]
It doesn't really matter for us, I was just commenting on how it is unfortunate that it does shadow within its own package. We could do package local nicknames, but I would rather not have a package accessor before a top level form, no technical reason, I just don't like it aesthetically. I want it to be more recognizable, and obvious what it does, which is why I came up with the name `defexportedclass`. Would that be OK?

**Comment by Ambrevar** [comment]
How do you think of doing it?  Defining your own macro?

(defmacro defexportedclass (...)
  (serapeum.exporting:defclass ...))

I find defexportedclass hard to read.  Maybe defclass-export instead?

Alternatively we can nickname the package "export" so it looks like

(export:defclass ...)

**Comment by jmercouris** [comment]
defclass-export, done!

**Comment by Ambrevar** [comment]
You need to export the macro if you want to use it in blocker-mode.

**Comment by jmercouris** [comment]
Ah, whoops :-)

thank you
