### ISSUE TITLE
Capture mouse scrolls

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#655]
We used to capture mouse scrolls in 1.5.  Now we don't, which works OK for scrolling except that we can't bind keys to button4 / button5 anymore :p

In particular, CUA users would like C-button4 / C-button5 to zoom in and out.
I suggest we capture the mouse scrolls.

We must pay attention to not break smooth scrolling.

**Comment by jmercouris** [comment]
I don't like capturing mouse scrolls, because of all the problems we had... if we can do it without introducing latency and/or causing problems, I'm all for it. Otherwise I do not think that C + Scroll is very important for zoom-in/out functionality for a typical CUA user. They may expect it, but it won't completely ruin the experience by being bound differently.

**Comment by Ambrevar** [comment]
Unlike before when we had to regenerate the bindings, I believe we can
now capture mouse scrolls properly.  I'll test.

**Comment by Ambrevar** [comment]
I'm on it.

**Comment by Ambrevar** [comment]
Done in af3e2362a2bc41e77b0fa2cd11615c96fa9c14c3.
