### ISSUE TITLE
The input area overlap screen

### ISSUE THREAD

**Issue by yuanjs** [atlas-engineer/next#69]
When use C-g to navigate, the input area will overlap the buttom screen.

**Comment by jmercouris** [comment]
I've spent many months thinking about this, and it is an unresolvable issue.

Consider this scenario: you are halfway down a page full of links, you use C-g, you scroll up so that the minibufffer is no longer blocking the links at the bottom.

In scrolling up, the links at the top are no longer visible. The only solution I can think of is the following, when at the bottom of the page, and invoking C-g, scroll up, otherwise, do nothing.

Does that make sense?
