### ISSUE TITLE
S- bindings (super) conflict with window managers

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/next#80]
In the documentation you consistently use `S-` as a prefix for the super key.  Emacs, however, uses `s-` for this while `S-` means the shift key.  Is this intentional?

That said, I think the super key should not be used by default since it is a commonly reserved prefix for window managers on Linux.

**Comment by jmercouris** [comment]
Hi, thank you for your interest!

To answer your first question, it is intentional. It has always bothered me that C, and M are capitalized whereas super is not capitalized. Since I do not plan on ever providing support for the shift modifier, I decided to break from tradition and make "S" for super. 

In terms of what are good defaults, perhaps you are right. I use macOS these days, and when I used to use i3, my special key was bound to alt instead of super, so it hasn't been a real problem for me. If you are willing to come up with an alternate set of default keybindings, designed with some good methodology and justification for your choices, I would consider merging them in.

thank you!

**Comment by Ambrevar** [comment]
Acknowledged.

Many windows managers and keyboard-based programs have a "modifier key" variable, such that the user can easily switch from, say, super to alt.
I guess this would probably be a good direction too for Next Browser.

Down that road, I see that most of the current bindings are Emacs-inspired, but they sometimes drift off in unexpected ways (in my opinion).
For instance, why `C-g`?  Why not `C-s` for search?  Etc.

I'll see if I have time next week to work on a rationale.  We could couple this with the issue around Evil bindings (#28) and create bindings sets.

**Comment by jmercouris** [comment]
This issue has been fixed :)

**Comment by hsanjuan** [comment]
Fixed how? How can I avoid S- conflicting with i3 ?

**Comment by jmercouris** [comment]
The super key is not used by default :-)

**Comment by hsanjuan** [comment]
Ok. I'm trying to follow: https://next.atlas.engineer/documentation#slime-with-a-compiled-version-of-next . Seems I can launch the swank server with M-x, but I don't have `slime-connect`,  do I need to compile in a special way?

**Comment by jmercouris** [comment]
`slime-connect` is in Emacs, in next you run M-x `start-swank`.

**Comment by hsanjuan** [comment]
Thanks, obviously I was too tired to pay enough attention to what I was reading..

**Comment by jmercouris** [comment]
No worries, happens to all of us :)
